### PR TITLE
BookStore: Add reducers and actions

### PR DESCRIPTION
**Pull request by sanieni6**
# BookStore: Add reducers and actions 🤓 
In this step, I implemented Redux Toolkit inside of a React application. I followed the next steps:
## Summary: 📖 
+ Add Redux Toolkit ✅ 
+ Create a directory that will contain all your Redux logic  ✅ 
+ Configure a Redux store  ✅ 
+ Define a slice of state for books  ✅ 
+ Define a slice of state for categories ✅ 
**Note: No changes in React components are required in this project.**

### CODE REVIEW

**Review by anagudelogu — CHANGES_REQUESTED** [review]
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @sanieni6, 
I'm Andres.

While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 



## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

- [x] You've done a great job working on your project documentation. 🚀 However, please make sure all the links present in your README file are working as expected, currently, your Contribution link is pointing to a different project (Todo List), and your LICENSE link is broken! 🤓 🔧 

image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sanieni6** [comment]
thanks for your review @anagudelogu

**Comment by sanieni6** [comment]
# Changes done 🟡 
+ Fix the broken License link in the readme file
+ Change the link to the Issue section on the readme file

**Review by rotimiazeez — APPROVED** [review]
Hi @sanieni6 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job fixing the required changes 👍🏽
- Good communication with the CR 👍🏽 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
